// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("AegisTasks.TasksLibrary")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Técnicas de Soft S.A.")]
[assembly: AssemblyProduct("AegisTasks")]
[assembly: AssemblyCopyright("Copyright © TECDESOFT 2025")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("D1A3F5C8-2E12-4F97-AB3B-8F7D1A4C9F2B")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.25.11.12")]
